//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace SNCFDI.Model
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/nomina")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/nomina", IsNullable = false)]
    public partial class Nomina
    {

        public Nomina()
        {
            this.Version = "1.1";
        }

        public Percepciones Percepciones { get; set; }

        public Deducciones Deducciones { get; set; }

        [System.Xml.Serialization.XmlArrayItemAttribute("Incapacidad", IsNullable = false)]
        public Incapacidad[] Incapacidades { get; set; }

        [System.Xml.Serialization.XmlArrayItemAttribute("HorasExtra", IsNullable = false)]
        public NominaHorasExtra[] HorasExtras { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RegistroPatronal { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumEmpleado { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CURP { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TipoRegimen { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumSeguridadSocial { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime FechaPago { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime FechaInicialPago { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime FechaFinalPago { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal NumDiasPagados { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Departamento { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string CLABE { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Banco { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime FechaInicioRelLaboral { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Antiguedad { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Puesto { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoContrato { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoJornada { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PeriodicidadPago { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SalarioBaseCotApor { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RiesgoPuesto { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SalarioDiarioIntegrado { get; set; }

    }

}

